stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

build:
  image: proxy-docker.sourdin.ovh/docker
  stage: build
  when: always
  script:
    - docker login repo-pub-docker.sourdin.ovh -u $REGISTRY_USER -p $REGISTRY_PASSWORD
    - docker build -t repo-pub-docker.sourdin.ovh/web/pelican:$CI_COMMIT_TAG .
    - docker push repo-pub-docker.sourdin.ovh/web/pelican:$CI_COMMIT_TAG
    - docker logout repo-pub-docker.sourdin.ovh
  rules:
    - if: $CI_COMMIT_TAG
